In [1]:
import numpy as np

In [2]:
# ways to create array
# indexing/slicing of array
# methods of array

In [3]:
# 1st way
np.array([3,4,2,23,5,23,45,67])

array([ 3,  4,  2, 23,  5, 23, 45, 67])

In [4]:
# 2nd way
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [8]:
# 3rd way
# linear space
np.linspace(1,20) # by default it will return 50 elements b/w given range

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [10]:
np.linspace(1, 20, num = 15) # it will return 15 elements b/w given range

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])

In [11]:
np.linspace(1, 20, num = 15, retstep=True) # it will return 15 elements b/w given range

(array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
         7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
        14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ]),
 1.3571428571428572)

In [12]:
# 4th way
np.empty([2,2])

array([[4.94065646e-324, 2.52304009e-258],
       [6.01347002e-154, 7.20358919e+159]])

In [13]:
# 5th way
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.identity(5) * 6

array([[6., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 6.]])

In [18]:
# 6th way
np.random.random() # by default returns a random number b/w 0 and 1

0.6838144706900027

In [19]:
np.random.random(4)

array([0.5992327 , 0.10521674, 0.60915349, 0.3783674 ])

In [21]:
np.random.random([4,4])

array([[0.78269976, 0.6015373 , 0.7430336 , 0.58715259],
       [0.47314745, 0.65709846, 0.24726248, 0.35678948],
       [0.11800185, 0.38294362, 0.30179576, 0.33918585],
       [0.36337842, 0.00880366, 0.58547367, 0.15978055]])

In [22]:
np.random.random(4) * 5

array([3.25714907, 2.10718053, 0.98594615, 3.90393511])

In [24]:
# random integers
np.random.randint(10,100)

38

In [25]:
np.random.randint(10,100,10)

array([33, 75, 71, 23, 18, 75, 23, 74, 85, 86])

In [26]:
np.random.randint(10,100,[3,4])

array([[22, 25, 15, 86],
       [99, 59, 69, 40],
       [35, 22, 18, 61]])

In [27]:
np.random.randn(5)

array([-0.94997063, -0.31785361, -0.87647368, -0.05949515, -3.24486186])

In [29]:
np.random.randn(3,4)

array([[ 0.45137918, -1.58207319,  1.48565917,  1.13872086],
       [-0.91562482,  0.44533464,  1.53877272, -0.17251433],
       [ 0.42248766, -1.09365367,  0.71349149,  0.21201903]])

In [31]:
# np.mean(np.random.randn(3,4))

In [32]:
# slicing of array

In [33]:
x = np.random.randint(1,100,15)

In [34]:
x

array([13, 37, 89, 89, 52, 57, 94, 49, 53, 75, 72, 19, 42,  7, 94])

In [35]:
x[0]

13

In [36]:
x[0:4]

array([13, 37, 89, 89])

In [37]:
x[-1]

94

In [40]:
x = np.random.randint(1,100,(5,5))

In [41]:
x

array([[38, 69, 23, 91, 63],
       [65, 52, 72, 24, 52],
       [28,  8,  3, 92, 78],
       [97, 91, 48, 97, 40],
       [28, 26, 79, 42, 56]])

In [42]:
x.ndim

2

In [43]:
x.shape

(5, 5)

In [44]:
x[0]

array([38, 69, 23, 91, 63])

In [45]:
x[1]

array([65, 52, 72, 24, 52])

In [46]:
x[0][0]

38

In [47]:
x[1][0]

65

In [48]:
x

array([[38, 69, 23, 91, 63],
       [65, 52, 72, 24, 52],
       [28,  8,  3, 92, 78],
       [97, 91, 48, 97, 40],
       [28, 26, 79, 42, 56]])

In [49]:
x[2][-1]

78

In [50]:
x[:]

array([[38, 69, 23, 91, 63],
       [65, 52, 72, 24, 52],
       [28,  8,  3, 92, 78],
       [97, 91, 48, 97, 40],
       [28, 26, 79, 42, 56]])

In [51]:
x[0:2]

array([[38, 69, 23, 91, 63],
       [65, 52, 72, 24, 52]])

In [52]:
x[:,0]

array([38, 65, 28, 97, 28])

In [53]:
x[:,1]

array([69, 52,  8, 91, 26])

In [54]:
x[:,1:3]

array([[69, 23],
       [52, 72],
       [ 8,  3],
       [91, 48],
       [26, 79]])

In [55]:
x[:, [0,3,4]]

array([[38, 91, 63],
       [65, 24, 52],
       [28, 92, 78],
       [97, 97, 40],
       [28, 42, 56]])

In [56]:
x[2:4, 2:4]

array([[ 3, 92],
       [48, 97]])

In [58]:
x[:,0:1]

array([[38],
       [65],
       [28],
       [97],
       [28]])

In [59]:
len(dir(np))

620

In [60]:
# methods

In [61]:
x = np.random.randint(1,100,15)

In [62]:
len(dir(x))

162

In [68]:
x

array([74, 72, 98, 10, 30, 59, 96, 77, 89, 20, 55, 74, 25, 91, 88])

In [64]:
np.min(x)

10

In [65]:
np.max(x)

98

In [66]:
np.sort(x)

array([10, 20, 25, 30, 55, 59, 72, 74, 74, 77, 88, 89, 91, 96, 98])

In [67]:
np.argmin(x)

3

In [69]:
np.argmax(x)

2

In [70]:
np.argsort(x)

array([ 3,  9, 12,  4, 10,  5,  1,  0, 11,  7, 14,  8, 13,  6,  2],
      dtype=int64)

In [71]:
np.mean(x)

63.86666666666667

In [72]:
np.median(x)

74.0

In [73]:
np.var(x)

811.848888888889

In [74]:
np.std(x)

28.49296209397838

In [78]:
np.quantile(x,0.5)

74.0

In [79]:
x.shape

(15,)

In [80]:
x.reshape((5,3))

array([[74, 72, 98],
       [10, 30, 59],
       [96, 77, 89],
       [20, 55, 74],
       [25, 91, 88]])

In [81]:
x = x.reshape((5,3))

In [82]:
# transpose
x.T

array([[74, 10, 96, 20, 25],
       [72, 30, 77, 55, 91],
       [98, 59, 89, 74, 88]])

In [83]:
np.mean(x)

63.86666666666667

In [84]:
# column wise
np.mean(x, 0)

array([45. , 65. , 81.6])

In [85]:
# row wise
np.mean(x, 1)

array([81.33333333, 33.        , 87.33333333, 49.66666667, 68.        ])

In [86]:
np.median(x, 1)

array([74., 30., 89., 55., 88.])

In [87]:
np.std(x, 1)

array([11.81336343, 20.11632836,  7.84573486, 22.36564826, 30.43024811])

In [88]:
# convert data to 1D
x.flatten()

array([74, 72, 98, 10, 30, 59, 96, 77, 89, 20, 55, 74, 25, 91, 88])

In [89]:
# x.reshape(3,-1)
# x.reshape(5,-1)
# x.reshape(-1,3)
x.reshape(-1,5)

array([[74, 72, 98, 10, 30],
       [59, 96, 77, 89, 20],
       [55, 74, 25, 91, 88]])

In [90]:
# hstack
# vstack
# r_
# c_
# concatenate

In [91]:
# np.where()