In [1]:
import sys, time
import numpy as np

In [2]:
np.array([4,3,5,7,7,2])

array([4, 3, 5, 7, 7, 2])

In [3]:
np.array([4,3,5,7,7,2,56.7,2.5])

array([ 4. ,  3. ,  5. ,  7. ,  7. ,  2. , 56.7,  2.5])

In [4]:
np.array([4,3,5,7,7,2,56.7,2.5,"hello"])

array(['4', '3', '5', '7', '7', '2', '56.7', '2.5', 'hello'], dtype='<U32')

## List vs Numpy Array 

In [5]:
# space complexity
list_1 = list()

In [6]:
sys.getsizeof(list_1)

56

In [7]:
arr_1 = np.array([])
sys.getsizeof(arr_1)

96

In [8]:
list_1 = [3,4]
sys.getsizeof(list_1)

72

In [9]:
arr_1 = np.array([3,4])
sys.getsizeof(arr_1)

104

In [12]:
list_1 = list(range(1,10000))
sys.getsizeof(list_1)

80048

In [13]:
arr_1 = np.array(list_1)
sys.getsizeof(arr_1)

40092

In [14]:
# time complexity

In [19]:
list_1 = list(range(1,10000000))
list_2 = list(range(1,10000000))
list_3 = []

start = time.time()

for i in range(len(list_1)):
    list_3.append(list_1[i] + list_2[i])

end = time.time()
total = end - start
print("Total time taken is ", total)

Total time taken is  4.641841888427734


In [20]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

start = time.time()

# broadcasting
arr_3 = arr_1 + arr_2

end = time.time()

total = end - start
print("Total time taken is ", total)

Total time taken is  0.03275632858276367


In [21]:
list_1 = list(range(1,10))

In [22]:
list_1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
np.array(list_1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
list_1 = [np.array(list_1)]

In [25]:
list_1

[array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [26]:
list_1[0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])